spring.application.name=Cocosnuss ResiliencePattern
server.port=1338

# Datenbank Konfiguration
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/Coco
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#JPA
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=none

# H2 explizit deaktivieren
spring.datasource.generate-unique-name=false
spring.sql.init.mode=never
spring.h2.console.enabled=false


# Retry
resilience4j.retry.instances.getAllOrdersRetry.maxAttempts=5
resilience4j.retry.instances.getAllOrdersRetry.waitDuration=1000ms
resilience4j.retry.instances.getAllOrdersRetry.ignoreExceptions=java.util.concurrent.TimeoutException

# Timeout
resilience4j.timelimiter.instances.getAllOrdersTimeout.timeoutDuration=10s
